<?php
/*
 * Project Euler problem 2:
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * From http://projecteuler.net/index.php?section=problems&id=2
 *
 * Implementation by Daniel Norris <shastao@gmail.com>
 * 
 */

function sumEvenFibonacci($limit)
{
    $sum = 0;
    $twoAgo = 0;
    $last = 1;

    while ($last < $limit)
    {
        $next = $twoAgo + $last;
        $twoAgo = $last;
        $last = $next;

        if ($last % 2 === 0)
        {
            $sum += $last;
        }
    }

    return $sum;
}

// main

echo sumEvenFibonacci(4000000);